---
version: "3.7"
services:
  ts-oauth-test:
    image: tailscale/tailscale:latest
    container_name: ts-oauth-test
    hostname: oauth-test
    environment:
      - TS_AUTHKEY=tskey-client-kG9vWmQvAJ11CNTRL-oXiZcGhEpN3htgQ6fwN5M3CPfEENcjR8N?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./ts-oauth-test/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  nginx-oauth-test:
    image: nginx
    network_mode: service:ts-oauth-test
